name: Canary

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  canary:
    name: Canary
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        deno: [canary]
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Setup zsh
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install zsh -y

      - name: Print Versions
        run: |
          which deno
          deno --version
          which bash
          bash --version
          which zsh
          zsh --version

      - name: Run tests
        run: deno test --unstable --shuffle --allow-all --jobs 8
