name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: Lint source
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint --unstable
