name: Test
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        deno: [v1.x]
    env:
      RUST_BACKTRACE: full
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Print Versions
        run: |
          deno --version
          which bash
          bash --version
          which /bin/bash
          /bin/bash --version

      - name: Run tests
        run: deno test --coverage=./cov --unstable --shuffle --allow-all --jobs 8

      - name: Generate lcov
        run: deno coverage --unstable --lcov ./cov > cov.lcov

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.deno }}
          files: cov.lcov
